### ISSUE TITLE
Description in protocol.txt needs fixing

### ISSUE THREAD

**Issue by tnias** [oxy-secure/oxy#106]
The paragraph explaining the KNOCK contains following:
> Message contents are a fixed-width (100 byte) value derived from hashing the knock key with the current number of seconds since the unix epoch modulo 60.

It's different in the [source](https://github.com/oxy-secure/oxy/blob/6fd7e30294507d8d742171b0aa4c222c9af4aa11/src/keys.rs#L104)

Maybe something like this:
> ... number of seconds since the unix epoch rounded down to the nearest multiple of 60.

**Comment by jennamagius** [comment]
Eyyyy, you're right. Thanks
