### ISSUE TITLE
Crash on downloading symlinked file

### ISSUE THREAD

**Issue by f0x52** [oxy-secure/oxy#111]
When I try to download a symlink, oxy crashes and gives:
```rust
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', libcore/result.rs:945:5
```

**Comment by jennamagius** [comment]
Hey, thanks for the report! I'll look into it :)

**Comment by jennamagius** [comment]
Looks like it's getting an incorrect filesize, then freaking out trying to draw WAY too much progress bar. Working on a fix now.

**Comment by jennamagius** [comment]
Fixed in dev: https://github.com/oxy-secure/oxy/commit/3c8347956ae41515d6aa63c67116965bd0521cad
