### ISSUE TITLE
inherits SSH protocol flaw: should use array of strings and exec the command directly

### ISSUE THREAD

**Issue by pabs3** [oxy-secure/oxy#113]
Oxy appears to inherit an SSH protocol flaw, it takes a single string on the wire and passes that directly to the shell. Instead the client should pass an array of NUL-terminated strings across the wire and the server should run the command directly using execv. This would avoid cross-host quoting issues and other shell meta-character issues.

**Comment by jennamagius** [comment]
Yeah, this seems legit. I'll make it work this way.

**Comment by jennamagius** [comment]
This could be implemented by adding new message types, but I'd rather break protocol compatibility and just rewrite 

    BasicCommand { command: String },
    PipeCommand { command: String },
    PtyRequest { command: Option<String> },

As 

    BasicCommand { command: Vec<String> },
    PipeCommand { command: Vec<String> },
    PtyRequest { command: Vec<String> },

pty_request.is_empty() could serve the same purpose as pty_request.is_none() does right now (running the multiplexer or the getpwent shell)

I'd rather pass unicode strings than C strings over the wire, just because unicode strings are a fundamental CBOR type. If a message comes in with unicode strings that contain nulls, just Reject { }

**Comment by jennamagius** [comment]
Implemented in dev: https://github.com/oxy-secure/oxy/commit/152c117c12e8480359fda02500bcff691f673b09

Let me know what you think.

**Comment by jennamagius** [comment]
Because of the vagaries of Clap, you have to use -- to pass mutiple command-values, so it'd go like:

oxy client my_server -- ls /etc /tmp

**Comment by andersk** [comment]
Thanks for giving this issue attention!

Instead of reimplementing `search_path`, you could just use [`execvp`](https://docs.rs/nix/0.11.0/nix/unistd/fn.execvp.html), right? `execvp` has slightly different behavior that users might expect, such as skipping over non-executable files.

**Comment by jennamagius** [comment]
Ah yeah, no, definitely. I'll swap it out for execvp, I just wasn't familiar.

**Comment by jennamagius** [comment]
Pushed: https://github.com/oxy-secure/oxy/commit/d68cd8ae2faed550383ff7c791c6cb53f28fb7b2

I think I may still wind up having to search PATH manually if I want to PATH-enable multiplexer_available. I definitely don't want to jump in to the multiplexer command with both feet if the multiplexer isn't actually available, but I _do_ want to make multiplexer happen by default when available.

**Comment by pabs3** [comment]
I don't know Rust but it looks much better to me.

Thanks for dropping shell support instead of keeping compatibility. 

-- 
bye,
pabs

http://bonedaddy.net/pabs3/

**Comment by jennamagius** [comment]
Thanks for the contribution!
