### ISSUE TITLE
cli to set up tun/tap forwarding?

### ISSUE THREAD

**Issue by dcarosone** [oxy-secure/oxy#124]
I may have missed it, but the only way I can see so far to create tun/tap forwards is from the interactive metacommand shell once a connection is started.  It might be nice to offer a way to do this from the external CLI directly.

**Comment by dcarosone** [comment]
oh, I guess I can use `-m` to run a metacommand post-connection.

Is that the intended UI, or should there be convenience options (like `-L`/`-R` for port-forwards) for this too?  This is very much a design question, since proliferation (and subsequent confusion) in openssh was clearly part of the problem there.

Assuming it's not common enough to warrant an external option, this issue can then be classed as a doc improvement with an example to help discovery of how to do this.

**Comment by jennamagius** [comment]
Implemented in dev https://github.com/oxy-secure/oxy/commit/c04e1bb416ac114fd8a9d5445cb8f55602fccf73

Thanks for the find!
