### ISSUE TITLE
Gateway Server

### ISSUE THREAD

**Issue by jennamagius** [oxy-secure/oxy#26]
Because the first message in key exchange is a plaintext client identifier, it should be possible for a server to inspect the client identifier, then proxy-forward all traffic in the connection to a destination chosen based on the client identifier without performing any encryption or decryption of its own. This could allow for "gateway servers" that sit on network externals and then forward connections to different servers on the internal based on the client key.

**Comment by jennamagius** [comment]
This can be used to allow multiple separated users to log in through a single TCP port without the server having to have CAP_SETUID: simply spawn a user-privileged server for each user, listening on a Unix socket. Then, have a nobody-owned dispatch process that owns the network port and dispatches traffic to the appropriate user-privileged server process.

**Comment by dcarosone** [comment]
Could this gateway also accept (and park) connections from reverse-servers?  If so, one could build a meetup service that stitches clients and server connections together, bypassing all sorts of firewall/nat restrictions, a bit like TeamViewer or zScaler's 'private access'.

I don't know if this can work without additions to the kex but it seems like it has great potential for ~~evil~~ user experience.

**Comment by jennamagius** [comment]
Using NoiseIKpsk1 instead of the existing kex turns this feature off entirely - that handshake renders it impossible to discern the long term key of the client unless you know the private key of the ultimate destination host.

That's a bit disappointing, because I do think this is a cool opportunity. That said, it's a result of the handshake just being straight-up stronger, so... I'm just gonna take it to the face on this one.
