### ISSUE TITLE
Have a manpage

### ISSUE THREAD

**Issue by jennamagius** [oxy-secure/oxy#53]
We already have fairly good interactive help thanks to Clap. The most ideal scenario is for the manpage to be procedurally derived from Clap information also. See github-dot-com/kbknapp/clap-rs/issues/552

**Comment by coderobe** [comment]
Here's a script that's able to generate the manpages for a given oxy (or Clap in general?) binary - https://github.com/coderobe/oxy-gen

The subcommands are split into their own manpages as is common with such programs (e.g. `git`)

**Comment by jennamagius** [comment]
This is really awesome, thank you!
